export const userData = [
  {
    id: 1,
    user_name: "John Doe",
    email: "john@example.com",
    phone: "123-456-7890",
    linkedin_url: "https://www.linkedin.com/in/johndoe",
    company: "ABC Corporation",
  },
  {
    id: 2,
    user_name: "Jane Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    linkedin_url: "https://www.linkedin.com/in/janesmith",
    company: "XYZ Ltd.",
  },
  {
    id: 3,
    user_name: "Michael Johnson",
    email: "michael@example.com",
    phone: "555-555-5555",
    linkedin_url: "https://www.linkedin.com/in/michaeljohnson",
    company: "Tech Innovators",
  },
  {
    id: 4,
    user_name: "John Doe",
    email: "john@example.com",
    phone: "123-456-7890",
    linkedin_url: "https://www.linkedin.com/in/johndoe",
    company: "ABC Corporation",
  },
  {
    id: 5,
    user_name: "Jane Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    linkedin_url: "https://www.linkedin.com/in/janesmith",
    company: "XYZ Ltd.",
  },
  {
    id: 6,
    user_name: "Michael Johnson",
    email: "michael@example.com",
    phone: "555-555-5555",
    linkedin_url: "https://www.linkedin.com/in/michaeljohnson",
    company: "Tech Innovators",
  },
  {
    id: 7,
    user_name: "John Doe",
    email: "john@example.com",
    phone: "123-456-7890",
    linkedin_url: "https://www.linkedin.com/in/johndoe",
    company: "ABC Corporation",
  },
  {
    id: 8,
    user_name: "Jane Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    linkedin_url: "https://www.linkedin.com/in/janesmith",
    company: "XYZ Ltd.",
  },
  {
    id: 9,
    user_name: "Michael Johnson",
    email: "michael@example.com",
    phone: "555-555-5555",
    linkedin_url: "https://www.linkedin.com/in/michaeljohnson",
    company: "Tech Innovators",
  },
  {
    id: 10,
    user_name: "John Doe",
    email: "john@example.com",
    phone: "123-456-7890",
    linkedin_url: "https://www.linkedin.com/in/johndoe",
    company: "ABC Corporation",
  },
  {
    id: 11,
    user_name: "Jane Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    linkedin_url: "https://www.linkedin.com/in/janesmith",
    company: "XYZ Ltd.",
  },
  {
    id: 12,
    user_name: "Michael Johnson",
    email: "michael@example.com",
    phone: "555-555-5555",
    linkedin_url: "https://www.linkedin.com/in/michaeljohnson",
    company: "Tech Innovators",
  },
  {
    id: 13,
    user_name: "John Doe",
    email: "john@example.com",
    phone: "123-456-7890",
    linkedin_url: "https://www.linkedin.com/in/johndoe",
    company: "ABC Corporation",
  },
  {
    id: 14,
    user_name: "Jane Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    linkedin_url: "https://www.linkedin.com/in/janesmith",
    company: "XYZ Ltd.",
  },
  {
    id: 15,
    user_name: "Michael Johnson",
    email: "michael@example.com",
    phone: "555-555-5555",
    linkedin_url: "https://www.linkedin.com/in/michaeljohnson",
    company: "Tech Innovators",
  },
  {
    id: 16,
    user_name: "John Doe",
    email: "john@example.com",
    phone: "123-456-7890",
    linkedin_url: "https://www.linkedin.com/in/johndoe",
    company: "ABC Corporation",
  },
  {
    id: 17,
    user_name: "Jane Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    linkedin_url: "https://www.linkedin.com/in/janesmith",
    company: "XYZ Ltd.",
  },
  {
    id: 18,
    user_name: "Michael Johnson",
    email: "michael@example.com",
    phone: "555-555-5555",
    linkedin_url: "https://www.linkedin.com/in/michaeljohnson",
    company: "Tech Innovators",
  },
  {
    id: 19,
    user_name: "John Doe",
    email: "john@example.com",
    phone: "123-456-7890",
    linkedin_url: "https://www.linkedin.com/in/johndoe",
    company: "ABC Corporation",
  },
  {
    id: 20,
    user_name: "Jane Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    linkedin_url: "https://www.linkedin.com/in/janesmith",
    company: "XYZ Ltd.",
  },
  {
    id: 50,
    user_name: "aaaaaaaaaa",
    email: "jane@example.com",
    phone: "987-654-3210",
    linkedin_url: "https://www.linkedin.com/in/janesmith",
    company: "XYZ Ltd.",
  },
  {
    id: 21,
    user_name: "Michael Johnson",
    email: "michael@example.com",
    phone: "555-555-5555",
    linkedin_url: "https://www.linkedin.com/in/michaeljohnson",
    company: "Tech Innovators",
  },
  {
    id: 22,
    user_name: "John Doe",
    email: "john@example.com",
    phone: "123-456-7890",
    linkedin_url: "https://www.linkedin.com/in/johndoe",
    company: "ABC Corporation",
  },
  {
    id: 23,
    user_name: "Jane Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    linkedin_url: "https://www.linkedin.com/in/janesmith",
    company: "XYZ Ltd.",
  },
  {
    id: 24,
    user_name: "Michael Johnson",
    email: "michael@example.com",
    phone: "555-555-5555",
    linkedin_url: "https://www.linkedin.com/in/michaeljohnson",
    company: "Tech Innovators",
  },
];
